// Generated by scripts/generate-oss-notices.mjs from package-lock.json — do not edit by hand.
// Regenerate after adding or upgrading a dependency. 257 packages as of soundgrid@0.8.7.

export interface OssNotice {
  name: string
  version: string
  license: string
}

export const OSS_NOTICES: OssNotice[] = [
  {
    "name": "@emnapi/runtime",
    "version": "1.11.3",
    "license": "MIT"
  },
  {
    "name": "@fontsource-variable/inter",
    "version": "5.3.0",
    "license": "OFL-1.1"
  },
  {
    "name": "@huggingface/jinja",
    "version": "0.5.10",
    "license": "MIT"
  },
  {
    "name": "@huggingface/tokenizers",
    "version": "0.1.3",
    "license": "Apache-2.0"
  },
  {
    "name": "@huggingface/transformers",
    "version": "4.2.0",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/colour",
    "version": "1.1.0",
    "license": "MIT"
  },
  {
    "name": "@img/sharp-darwin-arm64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-darwin-x64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-libvips-darwin-arm64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-darwin-x64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linux-arm",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linux-arm64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linux-ppc64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linux-riscv64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linux-s390x",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linux-x64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linuxmusl-arm64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-libvips-linuxmusl-x64",
    "version": "1.2.4",
    "license": "LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-linux-arm",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linux-arm64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linux-ppc64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linux-riscv64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linux-s390x",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linux-x64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linuxmusl-arm64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-linuxmusl-x64",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "@img/sharp-wasm32",
    "version": "0.34.5",
    "license": "Apache-2.0 AND LGPL-3.0-or-later AND MIT"
  },
  {
    "name": "@img/sharp-win32-arm64",
    "version": "0.34.5",
    "license": "Apache-2.0 AND LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-win32-ia32",
    "version": "0.34.5",
    "license": "Apache-2.0 AND LGPL-3.0-or-later"
  },
  {
    "name": "@img/sharp-win32-x64",
    "version": "0.34.5",
    "license": "Apache-2.0 AND LGPL-3.0-or-later"
  },
  {
    "name": "@jridgewell/gen-mapping",
    "version": "0.3.13",
    "license": "MIT"
  },
  {
    "name": "@jridgewell/remapping",
    "version": "2.3.5",
    "license": "MIT"
  },
  {
    "name": "@jridgewell/resolve-uri",
    "version": "3.1.2",
    "license": "MIT"
  },
  {
    "name": "@jridgewell/sourcemap-codec",
    "version": "1.5.5",
    "license": "MIT"
  },
  {
    "name": "@jridgewell/trace-mapping",
    "version": "0.3.31",
    "license": "MIT"
  },
  {
    "name": "@oxc-project/types",
    "version": "0.147.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-android-arm-eabi",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-android-arm64",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-darwin-arm64",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-darwin-x64",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-freebsd-x64",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-arm-gnueabihf",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-arm-musleabihf",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-arm64-gnu",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-arm64-musl",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-ppc64-gnu",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-riscv64-gnu",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-riscv64-musl",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-s390x-gnu",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-x64-gnu",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-linux-x64-musl",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-openharmony-arm64",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-win32-arm64-msvc",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-win32-ia32-msvc",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@oxlint/binding-win32-x64-msvc",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "@protobufjs/aspromise",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/base64",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/codegen",
    "version": "2.0.5",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/eventemitter",
    "version": "1.1.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/fetch",
    "version": "1.1.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/float",
    "version": "1.0.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/path",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/pool",
    "version": "1.1.0",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@protobufjs/utf8",
    "version": "1.1.2",
    "license": "BSD-3-Clause"
  },
  {
    "name": "@rolldown/binding-android-arm-eabi",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-android-arm64",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-darwin-arm64",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-darwin-x64",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-freebsd-x64",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-arm-gnueabihf",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-arm64-gnu",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-arm64-musl",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-ppc64-gnu",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-s390x-gnu",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-x64-gnu",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-linux-x64-musl",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-openharmony-arm64",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-win32-arm64-msvc",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/binding-win32-x64-msvc",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "@rolldown/pluginutils",
    "version": "1.0.1",
    "license": "MIT"
  },
  {
    "name": "@standard-schema/spec",
    "version": "1.1.0",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/node",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-android-arm64",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-darwin-arm64",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-darwin-x64",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-freebsd-x64",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-linux-arm-gnueabihf",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-linux-arm64-gnu",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-linux-arm64-musl",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-linux-x64-gnu",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-linux-x64-musl",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-win32-arm64-msvc",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/node/node_modules/lightningcss-win32-x64-msvc",
    "version": "1.32.0",
    "license": "MPL-2.0"
  },
  {
    "name": "@tailwindcss/oxide",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-android-arm64",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-darwin-arm64",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-darwin-x64",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-freebsd-x64",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-linux-arm-gnueabihf",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-linux-arm64-gnu",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-linux-arm64-musl",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-linux-x64-gnu",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-linux-x64-musl",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi/node_modules/@emnapi/core",
    "version": "1.11.1",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi/node_modules/@emnapi/runtime",
    "version": "1.11.1",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi/node_modules/@emnapi/wasi-threads",
    "version": "1.2.2",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi/node_modules/@napi-rs/wasm-runtime",
    "version": "1.1.4",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi/node_modules/@tybys/wasm-util",
    "version": "0.10.2",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-wasm32-wasi/node_modules/tslib",
    "version": "2.8.1",
    "license": "0BSD"
  },
  {
    "name": "@tailwindcss/oxide-win32-arm64-msvc",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/oxide-win32-x64-msvc",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@tailwindcss/vite",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "@types/chai",
    "version": "5.2.3",
    "license": "MIT"
  },
  {
    "name": "@types/deep-eql",
    "version": "4.0.2",
    "license": "MIT"
  },
  {
    "name": "@types/estree",
    "version": "1.0.9",
    "license": "MIT"
  },
  {
    "name": "@types/node",
    "version": "24.13.3",
    "license": "MIT"
  },
  {
    "name": "@types/react",
    "version": "19.2.18",
    "license": "MIT"
  },
  {
    "name": "@types/react-dom",
    "version": "19.2.5",
    "license": "MIT"
  },
  {
    "name": "@types/webmidi",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "@types/wicg-file-system-access",
    "version": "2023.10.7",
    "license": "MIT"
  },
  {
    "name": "@vitejs/plugin-react",
    "version": "6.1.0",
    "license": "MIT"
  },
  {
    "name": "@vitest/expect",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "@vitest/mocker",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "@vitest/pretty-format",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "@vitest/runner",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "@vitest/snapshot",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "@vitest/spy",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "@vitest/utils",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "acorn",
    "version": "8.18.0",
    "license": "MIT"
  },
  {
    "name": "acorn-jsx",
    "version": "5.3.2",
    "license": "MIT"
  },
  {
    "name": "acorn-jsx-walk",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "acorn-loose",
    "version": "8.5.2",
    "license": "MIT"
  },
  {
    "name": "acorn-walk",
    "version": "8.3.5",
    "license": "MIT"
  },
  {
    "name": "adm-zip",
    "version": "0.5.18",
    "license": "MIT"
  },
  {
    "name": "ansi-styles",
    "version": "4.3.0",
    "license": "MIT"
  },
  {
    "name": "assertion-error",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "boolean",
    "version": "3.2.0",
    "license": "MIT"
  },
  {
    "name": "chai",
    "version": "6.2.2",
    "license": "MIT"
  },
  {
    "name": "chalk",
    "version": "4.1.2",
    "license": "MIT"
  },
  {
    "name": "color-convert",
    "version": "2.0.1",
    "license": "MIT"
  },
  {
    "name": "color-name",
    "version": "1.1.4",
    "license": "MIT"
  },
  {
    "name": "commander",
    "version": "15.0.0",
    "license": "MIT"
  },
  {
    "name": "convert-source-map",
    "version": "2.0.0",
    "license": "MIT"
  },
  {
    "name": "csstype",
    "version": "3.2.3",
    "license": "MIT"
  },
  {
    "name": "define-data-property",
    "version": "1.1.4",
    "license": "MIT"
  },
  {
    "name": "define-properties",
    "version": "1.2.1",
    "license": "MIT"
  },
  {
    "name": "dependency-cruiser",
    "version": "18.2.0",
    "license": "MIT"
  },
  {
    "name": "dependency-cruiser/node_modules/picomatch",
    "version": "4.0.5",
    "license": "MIT"
  },
  {
    "name": "detect-libc",
    "version": "2.1.2",
    "license": "Apache-2.0"
  },
  {
    "name": "detect-node",
    "version": "2.1.0",
    "license": "MIT"
  },
  {
    "name": "enhanced-resolve",
    "version": "5.24.5",
    "license": "MIT"
  },
  {
    "name": "es-define-property",
    "version": "1.0.1",
    "license": "MIT"
  },
  {
    "name": "es-errors",
    "version": "1.3.0",
    "license": "MIT"
  },
  {
    "name": "es-module-lexer",
    "version": "2.3.2",
    "license": "MIT"
  },
  {
    "name": "es6-error",
    "version": "4.1.1",
    "license": "MIT"
  },
  {
    "name": "escape-string-regexp",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "estree-walker",
    "version": "3.0.3",
    "license": "MIT"
  },
  {
    "name": "expect-type",
    "version": "1.4.0",
    "license": "Apache-2.0"
  },
  {
    "name": "fdir",
    "version": "6.5.0",
    "license": "MIT"
  },
  {
    "name": "flatbuffers",
    "version": "25.9.23",
    "license": "Apache-2.0"
  },
  {
    "name": "fsevents",
    "version": "2.3.3",
    "license": "MIT"
  },
  {
    "name": "function-bind",
    "version": "1.1.2",
    "license": "MIT"
  },
  {
    "name": "global-agent",
    "version": "3.0.0",
    "license": "BSD-3-Clause"
  },
  {
    "name": "global-directory",
    "version": "4.0.1",
    "license": "MIT"
  },
  {
    "name": "globalthis",
    "version": "1.0.4",
    "license": "MIT"
  },
  {
    "name": "gopd",
    "version": "1.2.0",
    "license": "MIT"
  },
  {
    "name": "graceful-fs",
    "version": "4.2.11",
    "license": "ISC"
  },
  {
    "name": "guid-typescript",
    "version": "1.0.9",
    "license": "ISC"
  },
  {
    "name": "has-flag",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "has-property-descriptors",
    "version": "1.0.2",
    "license": "MIT"
  },
  {
    "name": "hasown",
    "version": "2.0.4",
    "license": "MIT"
  },
  {
    "name": "idb-keyval",
    "version": "6.3.0",
    "license": "Apache-2.0"
  },
  {
    "name": "ignore",
    "version": "7.0.6",
    "license": "MIT"
  },
  {
    "name": "ini",
    "version": "4.1.1",
    "license": "ISC"
  },
  {
    "name": "interpret",
    "version": "3.1.1",
    "license": "MIT"
  },
  {
    "name": "is-core-module",
    "version": "2.16.2",
    "license": "MIT"
  },
  {
    "name": "is-installed-globally",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "is-path-inside",
    "version": "4.0.0",
    "license": "MIT"
  },
  {
    "name": "jiti",
    "version": "2.7.0",
    "license": "MIT"
  },
  {
    "name": "json-stringify-safe",
    "version": "5.0.1",
    "license": "ISC"
  },
  {
    "name": "json5",
    "version": "2.2.3",
    "license": "MIT"
  },
  {
    "name": "kleur",
    "version": "3.0.3",
    "license": "MIT"
  },
  {
    "name": "lightningcss",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-android-arm64",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-darwin-arm64",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-darwin-x64",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-freebsd-x64",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-linux-arm-gnueabihf",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-linux-arm64-gnu",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-linux-arm64-musl",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-linux-x64-gnu",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-linux-x64-musl",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-win32-arm64-msvc",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "lightningcss-win32-x64-msvc",
    "version": "1.33.0",
    "license": "MPL-2.0"
  },
  {
    "name": "long",
    "version": "5.3.2",
    "license": "Apache-2.0"
  },
  {
    "name": "magic-string",
    "version": "0.30.21",
    "license": "MIT"
  },
  {
    "name": "matcher",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "minimist",
    "version": "1.2.8",
    "license": "MIT"
  },
  {
    "name": "nanoid",
    "version": "3.3.18",
    "license": "MIT"
  },
  {
    "name": "object-keys",
    "version": "1.1.1",
    "license": "MIT"
  },
  {
    "name": "obug",
    "version": "2.1.4",
    "license": "MIT"
  },
  {
    "name": "onnxruntime-common",
    "version": "1.24.3",
    "license": "MIT"
  },
  {
    "name": "onnxruntime-node",
    "version": "1.24.3",
    "license": "MIT"
  },
  {
    "name": "onnxruntime-web",
    "version": "1.26.0-dev.20260416-b7804b056c",
    "license": "MIT"
  },
  {
    "name": "onnxruntime-web/node_modules/onnxruntime-common",
    "version": "1.24.0-dev.20251116-b39e144322",
    "license": "MIT"
  },
  {
    "name": "oxlint",
    "version": "1.80.0",
    "license": "MIT"
  },
  {
    "name": "path-parse",
    "version": "1.0.7",
    "license": "MIT"
  },
  {
    "name": "pathe",
    "version": "2.0.3",
    "license": "MIT"
  },
  {
    "name": "picocolors",
    "version": "1.1.1",
    "license": "ISC"
  },
  {
    "name": "picomatch",
    "version": "4.0.7",
    "license": "MIT"
  },
  {
    "name": "platform",
    "version": "1.3.6",
    "license": "MIT"
  },
  {
    "name": "playwright",
    "version": "1.63.0",
    "license": "Apache-2.0"
  },
  {
    "name": "playwright-core",
    "version": "1.63.0",
    "license": "Apache-2.0"
  },
  {
    "name": "postcss",
    "version": "8.5.26",
    "license": "MIT"
  },
  {
    "name": "prompts",
    "version": "2.4.2",
    "license": "MIT"
  },
  {
    "name": "protobufjs",
    "version": "7.6.6",
    "license": "BSD-3-Clause"
  },
  {
    "name": "react",
    "version": "19.2.8",
    "license": "MIT"
  },
  {
    "name": "react-dom",
    "version": "19.2.8",
    "license": "MIT"
  },
  {
    "name": "rechoir",
    "version": "0.8.0",
    "license": "MIT"
  },
  {
    "name": "regexp-tree",
    "version": "0.1.27",
    "license": "MIT"
  },
  {
    "name": "resolve",
    "version": "1.22.12",
    "license": "MIT"
  },
  {
    "name": "roarr",
    "version": "2.15.4",
    "license": "BSD-3-Clause"
  },
  {
    "name": "rolldown",
    "version": "1.2.6",
    "license": "MIT"
  },
  {
    "name": "safe-regex",
    "version": "2.1.1",
    "license": "MIT"
  },
  {
    "name": "scheduler",
    "version": "0.27.0",
    "license": "MIT"
  },
  {
    "name": "semver",
    "version": "7.8.5",
    "license": "ISC"
  },
  {
    "name": "semver-compare",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "serialize-error",
    "version": "7.0.1",
    "license": "MIT"
  },
  {
    "name": "sharp",
    "version": "0.34.5",
    "license": "Apache-2.0"
  },
  {
    "name": "siginfo",
    "version": "2.0.0",
    "license": "ISC"
  },
  {
    "name": "sisteransi",
    "version": "1.0.5",
    "license": "MIT"
  },
  {
    "name": "source-map-js",
    "version": "1.2.1",
    "license": "BSD-3-Clause"
  },
  {
    "name": "sprintf-js",
    "version": "1.1.3",
    "license": "BSD-3-Clause"
  },
  {
    "name": "stackback",
    "version": "0.0.2",
    "license": "MIT"
  },
  {
    "name": "std-env",
    "version": "4.2.0",
    "license": "MIT"
  },
  {
    "name": "strip-bom",
    "version": "3.0.0",
    "license": "MIT"
  },
  {
    "name": "supports-color",
    "version": "7.2.0",
    "license": "MIT"
  },
  {
    "name": "supports-preserve-symlinks-flag",
    "version": "1.0.0",
    "license": "MIT"
  },
  {
    "name": "tailwindcss",
    "version": "4.3.3",
    "license": "MIT"
  },
  {
    "name": "tapable",
    "version": "2.3.3",
    "license": "MIT"
  },
  {
    "name": "tinybench",
    "version": "2.9.0",
    "license": "MIT"
  },
  {
    "name": "tinyexec",
    "version": "1.3.0",
    "license": "MIT"
  },
  {
    "name": "tinyglobby",
    "version": "0.2.17",
    "license": "MIT"
  },
  {
    "name": "tinyrainbow",
    "version": "3.1.1",
    "license": "MIT"
  },
  {
    "name": "tsconfig-paths",
    "version": "4.2.0",
    "license": "MIT"
  },
  {
    "name": "tsconfig-paths-webpack-plugin",
    "version": "4.2.0",
    "license": "MIT"
  },
  {
    "name": "tslib",
    "version": "2.8.1",
    "license": "0BSD"
  },
  {
    "name": "type-fest",
    "version": "0.13.1",
    "license": "(MIT OR CC0-1.0)"
  },
  {
    "name": "typescript",
    "version": "6.0.3",
    "license": "Apache-2.0"
  },
  {
    "name": "undici-types",
    "version": "7.18.2",
    "license": "MIT"
  },
  {
    "name": "vite",
    "version": "8.2.2",
    "license": "MIT"
  },
  {
    "name": "vitest",
    "version": "4.1.11",
    "license": "MIT"
  },
  {
    "name": "watskeburt",
    "version": "6.0.0",
    "license": "MIT"
  },
  {
    "name": "why-is-node-running",
    "version": "2.3.0",
    "license": "MIT"
  },
  {
    "name": "zustand",
    "version": "5.0.15",
    "license": "MIT"
  }
]
